version: '3'
services:
  postgres: 
    image: postgres
    container_name: "my_postgres"
    ports:
      - "35432:5432"
    environment:
      POSTGRES_PASSWORD: pass
  node-app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:  
      DATABASE_URL: postgres://postgres:pass@postgres:5432/postgres
    command: nodemon .    