version: '3'
services:
  postgres: 
    image: postgres
    ports:
      - "35432:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data  
    environment:
      POSTGRES_PASSWORD: pass
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app  
    command: nodemon .    